version: '3.8'

services:
  # WordPress with MySQL
  wordpress:
    image: wordpress:latest
    container_name: tbgs-wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress-uploads:/var/www/html/wp-content/uploads
      - ./wordpress-plugins:/var/www/html/wp-content/plugins
      - ./wordpress-themes:/var/www/html/wp-content/themes
    depends_on:
      - mysql
    networks:
      - tbgs-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: tbgs-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tbgs-network

  # phpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tbgs-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress_password
    depends_on:
      - mysql
    networks:
      - tbgs-network

volumes:
  wordpress_data:
  mysql_data:

networks:
  tbgs-network:
    driver: bridge